;; GENERAL
(require 'base-config)
(require 'base-functions)
(require 'base-keybinds)
(require 'base-theme)
(require 'base-vendor)

(require 'init-company)
(require 'init-counsel)
(require 'init-dap)
(require 'init-flycheck)
(require 'init-general)
(require 'init-ivy)
(require 'init-lsp)
(require 'init-projectile)
(require 'init-yas)

;; LANGUAGE SPECIFIC

;;(require 'lang-csharp)
(require 'lang-docker)
(require 'lang-elixir)
(require 'lang-git)
(require 'lang-java)
(require 'lang-k8s)
(require 'lang-org)
(require 'lang-php)
(require 'lang-plantuml)
(require 'lang-python)
(require 'lang-ruby)
(require 'lang-rust)
(require 'lang-web)
(require 'lang-yaml)

(provide 'base)
